define([], function() {
    return {
      "PropertyPaneDescription": "Description",
      "BasicGroupName": "Group Name",
      "DescriptionFieldLabel": "Description Field",
      "Months": ["Январь", "Февраль", "Март", "Апрель", "Май", "Июнь", "Июль", "Август", "Сентябрь", "Октябрь", "Ноябрь", "Декабрь"],
      "ShortMonths": ["Янв", "Фев", "Мар", "Апр", "Май", "Июн", "Июл", "Авг", "Сен", "Окт", "Ноя", "Дек"],
      "Days": ["Воскресенье", "Понедельник", "Вторник", "Среда", "Четверг", "Пятница", "Суббота"],
      "ShortDays": ["Вс", "Пн", "Вт", "Ср", "Чт", "Пт", "Сб"],
      "GoToToday": "Сегодня",
      "PrevMonthAriaLabel": "Предыдущий месяц",
      "NextMonthAriaLabel": "Следующий месяц",
      "PrevYearAriaLabel": "Предыдущий год",
      "NextYearAriaLabel": "Следующий год",
      "DatePickerPlaceholder": "Выберите дату...",
      "RequiredErrorMessage" : "Пожалуйста, заполните все обязательные поля",
      "NoResultsMessage": "Записей не найдено",
      "NewItemText": "Создать",
      "FormPanelHeaderText": "Новая запись",
      "StartDateLabelText": "Дата начала",
      "EndDateLabelText": "Дата окончания",
      "LeaveTypeLabelText": "Тип отсутствия",
      "SaveButtonText": "Сохранить",
      "CancelButtonText": "Отмена",
    }
  });